DROP DATABASE IF EXISTS regroupement00q7;
CREATE DATABASE regroupement00q7;
USE regroupement00q7;

CREATE TABLE country (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	CONSTRAINT `country_name_unique`
		UNIQUE (name),
	code VARCHAR(255) NOT NULL,
	CONSTRAINT `country_code_unique`
		UNIQUE (code),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE state (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(255) NOT NULL,
	CONSTRAINT `state_code_unique`
		UNIQUE (code),
	country_id BIGINT UNSIGNED DEFAULT NULL,
	CONSTRAINT `state_country_id_foreign`
		FOREIGN KEY (country_id) REFERENCES country (id)
		ON UPDATE RESTRICT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE address (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	line1 VARCHAR(255) NOT NULL,
	line2 VARCHAR(255) DEFAULT NULL,
	line3 VARCHAR(255) DEFAULT NULL,
	city VARCHAR(255) NOT NULL,
	zip VARCHAR(255) DEFAULT NULL,
	country_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `address_country_id_foreign`
		FOREIGN KEY (country_id) REFERENCES country (id)
		ON UPDATE RESTRICT,
	state_id BIGINT UNSIGNED DEFAULT NULL,
	CONSTRAINT `address_state_id_foreign`
		FOREIGN KEY (state_id) REFERENCES state (id)
		ON UPDATE RESTRICT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE addresstype (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE address_addresstypes (
	address_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `address_addresstypes_address_id_foreign`
		FOREIGN KEY (address_id) REFERENCES address (id)
		ON UPDATE RESTRICT,
	addresstype_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `address_addresstypes_addresstype_id_foreign`
		FOREIGN KEY (addresstype_id) REFERENCES addresstype (id)
		ON UPDATE RESTRICT,
	PRIMARY KEY (address_id, addresstype_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE role (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(255) NOT NULL,
	CONSTRAINT `role_code_unique`
		UNIQUE (code),
	description TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE permission (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(255) NOT NULL,
	CONSTRAINT `permission_code_unique`
		UNIQUE (code),
	description TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE roles_permissions (
	role_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `roles_permissions_role_id_foreign`
		FOREIGN KEY (role_id) REFERENCES role (id)
		ON UPDATE RESTRICT,
	permission_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `roles_permissions_permission_id_foreign`
		FOREIGN KEY (permission_id) REFERENCES permission (id)
		ON UPDATE RESTRICT,
	PRIMARY KEY (role_id, permission_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	CONSTRAINT `user_username_unique`
		UNIQUE (username),
	password VARCHAR(255) NOT NULL,
	is_active BOOLEAN NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE user_roles (
	user_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `user_roles_user_id_foreign`
		FOREIGN KEY (user_id) REFERENCES user (id)
		ON UPDATE RESTRICT,
	role_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `user_roles_role_id_foreign`
		FOREIGN KEY (role_id) REFERENCES role (id)
		ON UPDATE RESTRICT,
	PRIMARY KEY (user_id, role_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_addresses (
	user_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `user_addresses_user_id_foreign`
		FOREIGN KEY (user_id) REFERENCES user (id)
		ON UPDATE RESTRICT,
	address_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `user_addresses_address_id_foreign`
		FOREIGN KEY (address_id) REFERENCES address (id)
		ON UPDATE RESTRICT,
	PRIMARY KEY (user_id, address_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE quadcopter (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `quadcopter_user_id_foreign`
		FOREIGN KEY (user_id) REFERENCES user (id)
		ON UPDATE RESTRICT,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	registration VARCHAR(255) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE parttype (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE part (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	parttype_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `part_parttype_id_foreign`
		FOREIGN KEY (parttype_id) REFERENCES parttype (id)
		ON UPDATE RESTRICT,
	quadcopter_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `part_quadcopter_id_foreign`
		FOREIGN KEY (quadcopter_id) REFERENCES quadcopter (id)
		ON UPDATE RESTRICT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE location (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	latitude VARCHAR(255) NOT NULL,
	longitude VARCHAR(255) NOT NULL,
	note TEXT DEFAULT NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `location_user_id_foreign`
		FOREIGN KEY (user_id) REFERENCES user (id)
		ON UPDATE RESTRICT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE logflight (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	log_date TIMESTAMP NULL,
	quadcopter_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `logflight_quadcopter_id_foreign`
		FOREIGN KEY (quadcopter_id) REFERENCES quadcopter (id)
		ON UPDATE RESTRICT,
	duration INT UNSIGNED NOT NULL,
	weather TEXT NOT NULL,
	location_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `logflight_location_id_foreign`
		FOREIGN KEY (location_id) REFERENCES location (id)
		ON UPDATE RESTRICT,
	note TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE logpartaction (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE logpart (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	log_date TIMESTAMP NULL,
	quadcopter_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `logpart_quadcopter_id_foreign`
		FOREIGN KEY (quadcopter_id) REFERENCES quadcopter (id)
		ON UPDATE RESTRICT,
	part_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `logpart_part_id_foreign`
        FOREIGN KEY (part_id) REFERENCES part (id)
        ON UPDATE RESTRICT,
	logpartaction_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `logpart_logpartaction_id_foreign`
		FOREIGN KEY (logpartaction_id) REFERENCES logpartaction (id)
		ON UPDATE RESTRICT,
	note TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);