USE regroupement00q7;
source outputs/insert_addresstypes.sql
source outputs/insert_country.sql
source outputs/insert_logpartactions.sql
source outputs/insert_parttypes.sql
source outputs/insert_permissions.sql
source outputs/insert_roles.sql
source outputs/insert_users.sql
source outputs/insert_states.sql
source outputs/insert_addresses.sql
source outputs/insert_address_addresstypes.sql
source outputs/insert_locations.sql
source outputs/insert_quadcopters.sql
source outputs/insert_logflights.sql
source outputs/insert_part_antennas.sql
source outputs/insert_part_cameras.sql
source outputs/insert_part_ESCs.sql
source outputs/insert_part_flight_controllers.sql
source outputs/insert_part_frames.sql
source outputs/insert_part_GPSs.sql
source outputs/insert_part_motors.sql
source outputs/insert_part_PDBs.sql
source outputs/insert_part_props.sql
source outputs/insert_part_radio_receivers.sql
source outputs/insert_part_video_transmitters.sql
source outputs/insert_part_voltage_regulators.sql
source outputs/insert_part_voltage_sensors.sql
source outputs/insert_logparts.sql
source outputs/insert_roles_permissions.sql
source outputs/insert_user_addresses.sql
source outputs/insert_user_roles.sql